worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/routing-map.frontend.conf;
  include /etc/nginx/logging.conf;
  include /etc/nginx/proxy.conf;

  resolver 127.0.0.11 ipv6=off valid=30s;

  upstream mindlet_dashboard { server dashboard:3000; }
  upstream mindlet_auth      { server auth:3000; }
  upstream mindlet_profile   { server profile:3000; }
  upstream mindlet_study     { server study:3000; }
  upstream mindlet_decks     { server decks:3000; }

  server {
    listen 80 default_server;
    server_name _;

    absolute_redirect off;
    port_in_redirect off;

    client_max_body_size 50m;

    location = / {
      return 302 /dashboard/;
    }

    location = /dashboard {
      return 302 /dashboard/;
    }
    location /dashboard/ {
      proxy_pass http://mindlet_dashboard/;
    }

    location = /auth {
      return 302 /auth/login;
    }
    location /auth/ {
      proxy_pass http://mindlet_auth/;
    }

    location = /profile {
      return 302 /profile/;
    }
    location /profile/ {
      proxy_pass http://mindlet_profile/;
    }

    location = /study {
      return 302 /study/;
    }
    location /study/ {
      proxy_pass http://mindlet_study/;
    }

    location = /decks {
      return 302 /decks/;
    }
    location /decks/ {
      proxy_pass http://mindlet_decks/;
    }
  }
}
