events {}
http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
  }

  upstream dashboard_upstream {
    server dashboard:3001;
  }
  upstream auth_upstream {
    server auth:3002;
  }
  upstream profile_upstream {
    server profile:3003;
  }
  upstream study_upstream {
    server study:3004;
  }
  upstream decks_upstream {
    server decks:3005;
  }

  server {
    listen 80;
    server_name localhost;

    location = / {
      return 302 /dashboard/;
    }

    location = /dashboard {
      return 302 /dashboard/;
    }
    location /dashboard/ {
      proxy_pass http://dashboard_upstream;
      include /etc/nginx/proxy.conf;
    }

    location = /auth {
      return 302 /auth/;
    }
    location /auth/ {
      proxy_pass http://auth_upstream;
      include /etc/nginx/proxy.conf;
    }

    location = /profile {
      return 302 /profile/;
    }
    location /profile/ {
      proxy_pass http://profile_upstream;
      include /etc/nginx/proxy.conf;
    }

    location = /study {
      return 302 /study/;
    }
    location /study/ {
      proxy_pass http://study_upstream;
      include /etc/nginx/proxy.conf;
    }

    location = /decks {
      return 302 /decks/;
    }
    location /decks/ {
      proxy_pass http://decks_upstream;
      include /etc/nginx/proxy.conf;
    }
  }
}
