map $uri $upstream_service {
    default      "-";
    =/           "redirect→dashboard";
    ~^/dashboard "dashboard";
    ~^/auth      "auth";
    ~^/profile   "profile";
    ~^/study     "study";
    ~^/decks     "decks";
}
